---
- name: Deploy RHELAI on top of existing RHOSO
  hosts: "{{ override_hosts | default('all', true) }}"
  strategy: linear
  gather_facts: "{{ gather_facts | default(false) }}"
  any_errors_fatal: true
  tasks:
    - ansible.builtin.import_role:
        name: setup_rhelai
        tasks_from: main.yml
    - ansible.builtin.import_role:
        name: setup_rhelai
        tasks_from: download_tools.yml
    - ansible.builtin.import_role:
        name: setup_rhelai
        tasks_from: install_crc.yml
    - ansible.builtin.import_role:
        name: setup_rhelai
        tasks_from: prepare_controlplane_config.yml
    - ansible.builtin.import_role:
        name: setup_rhelai
        tasks_from: deploy_controlplane.yml
    - ansible.builtin.import_role:
        name: setup_rhelai
        tasks_from: deploy_dataplane.yml
    - ansible.builtin.import_role:
        name: setup_rhelai
        tasks_from: deploy_rhelai.yml