apiVersion: dataplane.openstack.org/v1beta1
kind: OpenStackDataPlaneService
metadata:
  name: tunneling
spec:
  playbookContents: |
    - hosts: all
      strategy: linear
      tasks:
        - name: Enable podified-repos
          become: true
          ansible.builtin.shell: |
            set -euxo pipefail

            EXISTS=false
            if [ -e "/etc/systemd/system/${TUN_NAME}.service" ]; then
                ovs-vsctl del-port br-ex ${TUN_NAME} || true
                EXISTS=true
            fi

            cat <<EOF > "/etc/systemd/system/${TUN_NAME}.service"
            [Unit]
            Description=Create ${TUN_NAME} bridge
            Requires=network-online.target
            After=network-online.target
            [Service]
            ExecStart=ovs-vsctl --may-exist add-port {{ neutron_physical_bridge_name }} ${TUN_NAME} -- set interface ${TUN_NAME} mtu_request=${MTU} type=geneve options:remote_ip=${TUN_IP} options:key=${GNV_ID}
            RemainAfterExit=true
            Type=oneshot
            [Install]
            WantedBy=multi-user.target edpm_ovn_controller.service
            EOF
            if [ -z "${EXISTS}" ]; then
                systemctl enable --now "${TUN_NAME}.service"
            else
                systemctl daemon-reload
                systemctl restart "${TUN_NAME}.service"
            fi
