---
# Copyright 2024 Red Hat, Inc.
# All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.

- name: Set up service input
  ansible.builtin.shell:
    chdir: "~/install_yamls"
    cmd: |
      source ~/oclogin && \
      NNCP_TIMEOUT={{ operators_timeout }} TIMEOUT={{ operators_timeout }} make input

- name: Install Openstack Operator index
  ansible.builtin.shell:
    chdir: "~/install_yamls"
    cmd: |
      source ~/oclogin && \
      NNCP_TIMEOUT={{ operators_timeout }} TIMEOUT={{ operators_timeout }} make openstack_wait

- name: Set kustomize path # We use don't Cinder by default
  ansible.builtin.set_fact:
    kustomize_template_path: "templates/kustomization-cinder.yaml"
  when: "deploy_cinder"

- name: Label cinder node
  ansible.builtin.shell:
    cmd: |
      source ~/oclogin && \
      oc label node --all openstack.org/cinder-lvm=
  when: "deploy_cinder"

- name: Setup template dir
  ansible.builtin.file:
    state: directory
    path: ~/templates

- name: Copy Template to host
  ansible.builtin.copy:
    src: "{{ kustomize_template_path }}"
    dest: ~/templates/kustomization.yaml

- name: Create kustomization inserting PCI vendor and product id
  ansible.builtin.shell:
    chdir: "~/install_yamls"
    cmd: |
      mkdir -p ./out/ctlplane
      sed 's/${VENDOR_ID}/{{ gpu_pci_vendor_id }}/g;s/${PRODUCT_ID}/{{ gpu_pci_id }}/g' ~/templates/kustomization.yaml > out/ctlplane/kustomization.yaml
    creates: ./out/ctlplane/kustomization.yaml

- name: Run kustomization
  ansible.builtin.shell:
    chdir: "~/install_yamls"
    cmd: "source ~/oclogin && oc kustomize ./out/ctlplane > ./out/openstack-deployment.yaml && sleep 60"
    creates: ./out/openstack-deployment.yaml

